### ISSUE TITLE
[vpn-policy-routing] Issue:

### ISSUE THREAD

**Issue by jief666** [stangri/openwrt_packages#110]
I got these errors when trying to start the service :
```
Failed to set up 'wan/eth0.2/192.168.0.1'
Failed to set up 'wwan//0.0.0.0'
Failed to set up 'VPN/tun0/10.8.0.2 \033[0;32m[\xe2\x9c\x93]\033[0m'
failed to set up any gateway
```

My router IP address is NOT 192.168.0.1.
So my question is : is '192.168.0.1' hard coded ?

**Comment by jief666** [comment]
Sorry, I misunderstood the message. 'wan/eth0.2/192.168.0.1' is the address of the gateway. which is correct on that interface.

In the end, I added . /lib/functions.sh at the beginning of the file '/etc/rc.d/S94vpn-policy-routing' to make it work.

Thanks.

**Comment by klonwar** [comment]
> . /lib/functions.sh

Could you please show your `S94vpn-policy-routing` file? I've tried everything, but still have the same error. 
My file content:
```bash
#!/bin/sh /etc/rc.common
# Copyright 2017-2020 Stan Grishin (stangri@melmac.net)
# shellcheck disable=SC2039,SC1091,SC2018,SC2019,SC3043,SC3057,SC3060

PKG_VERSION='0.3.5-3'

# sysctl net.ipv4.conf.default.rp_filter=1
# sysctl net.ipv4.conf.all.rp_filter=1

# shellcheck disable=SC2034
START=94
# shellcheck disable=SC2034
USE_PROCD=1

if type extra_command 1>/dev/null 2>&1; then
...
```

When I'm trying to start service from command line it fails with error `"ip rule show" does not take any arguments` in `ip -4 rule list fwmark "${mark}/${fwMask}" table "$tid"`

And `ipv4_error` becomes true here
```
while read -r i; do
	idev="$(echo "$i" | grep -Eso 'dev [^ ]*' | awk '{print $2}')"
	if ! is_supported_iface_dev "$idev"; then
		ip -4 route add $i table "$tid" >/dev/null 2>&1 || ipv4_error=1 # RTNETLINK answers: File exists
	fi
done
```

**Comment by stangri** [comment]
@klonwar could you please check if you have `ip` or `ip-full` package installed? if you replace `list` with `ls` in the `ip` command does it help? If you have just `ip` package, can you please try `ip-full`? 

Thanks!

**Comment by klonwar** [comment]
> could you please check if you have ip or ip-full package installed

Yes, I have `ip-full` package installed. 
![image](https://user-images.githubusercontent.com/12374932/133208643-a4c00351-a1f1-4eec-a3d3-3f646c0c01c5.png)

With `ls` in `ip` command it still trows `"ip rule show" does not take any arguments.` error. 

Сan this error appear because I have an old version of openwrt (15.05.1)?

**Comment by stangri** [comment]
Oh, I don't think it's been tested on CC. Have you tried turning off the IPv6 support?

**Comment by klonwar** [comment]
Yes, it's already disabled. I guess I just need to install the latest version of openwrt. I'll try this later
![image](https://user-images.githubusercontent.com/12374932/133602519-c9626a4c-16e3-4290-b186-28e40ca84cb6.png)

**Comment by stangri** [comment]
Sorry, you may want to try an earlier version of `vpn-policy-routing` (like 0.2.x), outside of that I can't help you making it work on 15.05.
