### ISSUE TITLE
GLAR300M loses connection and does not reboot after install of slider-support

### ISSUE THREAD

**Issue by QXMP** [stangri/openwrt_packages#113]
I am trying to install the slider-package on my GL-AR300M-ext but after installation through SSH
the GL-AR300M-ext loses connection and does not reboot.

OpenWrt version : OpenWrt 18.06.1 r7258-5eb055306f / LuCI openwrt-18.06 branch (git-18.196.56128-9112198)
firmware used  : openwrt-ar300m-nand-3.104.tar

Any help will be highly appreciated.

**Comment by stangri** [comment]
Why 18.06.1? 

Is it GL-Inet's flavour or vanilla OpenWrt? 

Are you able to capture the system log?

**Comment by QXMP** [comment]
Hi Stan,

Thanks for your quick response! Can we also PM ? Would like to provide some further background and request services if possible.

Regards,
Michel
