### ISSUE TITLE
[slider-support] Issue:  not working 

### ISSUE THREAD

**Issue by mantheman** [stangri/openwrt_packages#114]
**Describe the bug**
Built Openwrt 19.07.3 for GL-AR150. Added "slider-support". 
Added support for AR150:
`gpio-8   (                    |BTN_8               ) in  hi`
so check-slider.ar150 includes `checkslider() { grep 'gpio-8.*hi' /sys/kernel/debug/gpio; }` (without the "auto" part that apparently the other supported routers have). Also added Travelmate and Relayd.

--
Started fresh, added my wifi to travelmate -> so far so good, everything works in normal router mode (the slider is nearest the reset button, and slider-support has not been triggered).
`cat /etc/config/slider-support` are the default values included in the package.

Switch slider to the right, and nothing happens. Did a little digging which led me to the config file that now says:
`option enabled ''\''1'\'''` . Changed this manually to `option enabled '1'`, then everything works as expected.

I think this is the bug: in file `slider-support.init`
```
set_enabled() { uci -q set "${packageName}.config.enabled='$1'"; uci commit "${packageName}"; }
```
change to:
```
set_enabled() { uci -q set "${packageName}.config.enabled=$1"; uci commit "${packageName}"; }

```
Also, why is the default configuration `enabled '0'`, but automatically get's changed to `enabled '1'` (well, as of right now it's ''\''1'\''') when I move the slider the first time? If it's not going to respect the enabled flag then why include it? It's no big deal for me since I want to have it enabled for my travel router anyways but you might want to take a look at it. Also I think it's a good idea to that have it enabled by default, since if you have a need for this package then you probably want it to be enabled by default:)

**Comment by mantheman** [comment]
[Fixed](https://github.com/stangri/openwrt_packages/commit/4c4856ce4300341ab7fbd33040671ffc36b7352d)

**Comment by stangri** [comment]
Sorry it took me a while to fully address. 

I've added support for AR150, could you please confirm the slider on it is BTN_1, like on AR300M and not BTN0 like on AR-750?

Package sets enabled/disabled on start/stop to make sure it is not reloaded/restarted when manually stopped.

PS. As you have noticed, I fixed the bug with quotes a few days ago, thanks!

**Comment by mantheman** [comment]
Hi. No, the slider on gl-ar150 is on BTN_8.

**Comment by stangri** [comment]
Thanks, fixed the Makefile for AR150 to include BTN_8.

Can you please elaborate on the whole `"auto" part`, I'm not sure I understand what you mean.

**Comment by mantheman** [comment]
I'm sorry, disregard that, I got things mixed up. I could have sweared that the checkslider function was something akin to this:
checkslider() { grep -q 'button left.***auto**.*hi' /sys/kernel/debug/gpio; }
