### ISSUE TITLE
[vpn-policy-routing] Wish: block routing

### ISSUE THREAD

**Issue by h4de5** [stangri/openwrt_packages#118]
**Is your feature request related to a problem? Please describe.**
I want to block certain devices from the internet. 
I am almost sure, that I could solve this, using the firewall page, but I don't like that interface over there - and I almost bricked a device the last time I fiddled around with iptables...

**Describe the solution you'd like**
there should be an additinal value for "block access" in the dropdown. 

**Describe alternatives you've considered**
I tried to simple create a new interface that is not bridged or forwarded to WAN - which showed up in the vpn-policy-routing dropdown eventually. but it failed with the following error - I think because the interface didn't have an IP:

```
ip_set xxx
Please unset 'src_addr', 'src_port' and 'dest_port' for policy "xxx"
```

**Additional context**
i would also appriciate it, ff you can tell me where my initial idea went wrong and how I can fix it!

best regards
PS: great work!

**Comment by stangri** [comment]
Have you tried to create fake/non-connected vpn interface and enabling strict policies?

That is, if you want to stick with vpn-policy-routing. You can ask at OpenWrt forum how to better solve your problem with OpenWrt's fw3.

**Comment by h4de5** [comment]
I didn't name it vpn but block. Would that make a difference? It was an unmanaged interface without any additional settings. But as it did not get an ip it seems vpn-policy-routing cannot use it for routing. Ill try to give it a static ip next
