### ISSUE TITLE
[bug] Save & Apply not having any effect after router reboot

### ISSUE THREAD

**Issue by ghost** [stangri/openwrt_packages#13]
Router Turri Omnia
OpenWrt omnia 15.05 r47055 / LuCI 526a8767846acbe57c521912b35feb4d97354db6 branch (git-18.145.30016-526a876)
Kernel 4.4.134-8f7f4132dc88fb7034ce9648e5961be5-0
luci-app-vpn-policy-routing | git-18.151.61791-fed3..-23
vpn-policy-routing | 0.0.2-2

---
mentioned https://forum.turris.cz/t/vpn-policy-based-routing-possible/7204/23

After updating the router's OS from TOS 3.10 to 3.10.1 and issue #7 the workaround of getting PBR to work after a reboot is not working anymore, as in pressing `Save & Apply `(/cgi-bin/luci/admin/services/vpn-policy-routing) is not having any effect.

Only way to get PBR after a router's reboot is connecting to the TO over ssh and then from the command line

`/etc/init.d/vpn-policy-routing reload`

**Comment by stangri** [comment]
Actually, nevermind that, if CLI reload is working, new dnsmasq restart method must be working too. Must be a change in luci in the new Turris fw.

**Comment by ghost** [comment]
luci-app-vpn-policy-routing git-18.181.76096-1fd3…-24
vpn-policy-routing 0.0.2-6
TOS 3.10.3

the issue is not apparent anymore
