### ISSUE TITLE
dnsmasq.ipset breaks luci-app-simple-adblock

### ISSUE THREAD

**Issue by wengole** [stangri/openwrt_packages#131]
Hi,

When I got into advanced tab in Luci for Simple Adblock, enable dnsmasq IP Set and hit save and apply, I am presented with the following error in the browser and am no longer able to manage Simple AdBlock

```/usr/lib/lua/luci/i18n.lua:48: bad argument #1 to 'format' (string expected, got nil)
stack traceback:
	[C]: in function 'format'
	/usr/lib/lua/luci/i18n.lua:48: in function 'translatef'
	/usr/lib/lua/luci/model/cbi/simple-adblock.lua:139: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1340: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1023: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>
```

Versions:
luci-app-simple-adblock	1.8.5-1-1
simple-adblock	1.8.4-10
luci	git-21.096.73306-254083c-1

**Comment by stangri** [comment]
What a great catch, that's a big one! I pushed a fixed IPK to my repo so you can just upgrade the luci app or if you don't have my repo added, you can download the updated IPK from here: https://dev.melmac.net/repo/luci-app-simple-adblock_1.8.7-3_all.ipk. I believe this newer version will work with the `simple-adblock` 1.8.4 you have installed.

If you're on OpenWrt 21.02 or later, I would also recommend you update the principal `simple-adblock` package to 1.8.7-3.

**Comment by stangri** [comment]
Oh, please let me know when you can test this, so I can merge related PRs.

**Comment by wengole** [comment]
That fixed it, thanks

**Comment by stangri** [comment]
Thanks for reporting this!
