### ISSUE TITLE
[vpn-policy-routing] Wish: Support for SQM

### ISSUE THREAD

**Issue by lynxthecat** [stangri/openwrt_packages#136]
VPN PBR in OpenWrt works very well, but absent very in-depth knowledge of SQM, it seems for the average user it is next to impossible to get a working implementation of SQM + VPN PBR. Some kind of SQM handling would be superb to ensure that users can retain effective SQM notwithstanding the use of VPN PBR. For example, let's say a user uses WireGuard and VPN PBR to bypass to WAN. Which interface should CAKE be applied upon? A new interface has to be created in the right way that retains both the VPN and bypassed flows. But doing so is very difficult at present.

**Comment by stangri** [comment]
VPR uses a specific fwmark in order to be compatible with the fwmarks used by SQM. Outside of that, I can't really help you, maybe SQM maintainer/creator would be of more help.
