### ISSUE TITLE
[vpn-policy-routing] Issue:

### ISSUE THREAD

**Issue by vstevenphan** [stangri/openwrt_packages#141]
I'm using OpenWRT on CR6608 Xiaomi. VPN and WAN Policy-Based Routing does not restart to recognize service gateways after I reboot the router. Therefore, all the Internet traffic goes through the Tun0 VPN interface. I tried to restart  VPN and WAN Policy-Based Routing and the routing worked. Any solution?

**Comment by stangri** [comment]
Consider adding any relevant information, like versions, log when the interfaces come up, etc.

**Comment by stangri** [comment]
Closing due to lack of actionable information.
