### ISSUE TITLE
[pbr] Issue: Routes are not re-added, after the interface's physical device being removed and re-added

### ISSUE THREAD

**Issue by imKnect** [stangri/openwrt_packages#150]
**Describe the bug**
Routes are not re-added, after the interface's physical device is removed and re-added

**My Environment**
1. Newly installed Openwrt 21.02.1 x86_64 official release
2. Newly installed pbr and luci-app-pbr, `Strict enforcement` set `false`

**To Reproduce**

1. Add a tun device (named `utun`), add a interface (name `CLASH`) binding that tun device (`utun`):

![image](https://user-images.githubusercontent.com/36035854/154055250-d3b94f33-2244-401e-8e01-946224817c74.png)

2. Add policy in pbr, `Strict enforcement` set `false` and check the routes: 

![image](https://user-images.githubusercontent.com/36035854/154056335-5dd5da25-4def-401e-b155-30b6e38e72e8.png)
![image](https://user-images.githubusercontent.com/36035854/154055466-3f384773-1ac5-4bdc-bcaf-92c03396eac5.png)

Routes (**remember the red one**): 

![image](https://user-images.githubusercontent.com/36035854/154055625-25051471-89eb-4fcf-a2d2-ca6978f4fd71.png)

3. Run `ip tuntap del utun mode tun`  to delete the `utun`, the iface `CLASH` down and pbr correctly change the the interface in policy to `WAN`

![image](https://user-images.githubusercontent.com/36035854/154057471-faa97633-ee1a-4d8d-99be-f5bda3a73c7a.png)
![image](https://user-images.githubusercontent.com/36035854/154057527-0e080b41-e7a5-4dc4-bbed-a357d0590fd3.png)

The route of `utun` disappeared

![image](https://user-images.githubusercontent.com/36035854/154057541-94479fba-5573-4582-8237-21122a9338c8.png)

4. Now run `ip tuntap add utun mode tun` to re-add `utun`, the iface `CLASH` up, and the pbr change the the interface in policy back to `CLASH`:

![image](https://user-images.githubusercontent.com/36035854/154058530-e7629f15-9fe9-487b-8711-bab9bc2dabde.png)

**BUT** the route of `utun` is still missing:

![image](https://user-images.githubusercontent.com/36035854/154058901-2a001ed4-eebe-4e60-8c24-35b6132e0cc4.png)

and the log can't provide any information.

**Expected behavior**
The routes should be added back after the tun dev being removed-and-re-add.

Now I am trying to modify the file `/etc/hotplug.d/iface/70-pbr`, changing the `reload_interface` to `restart` as a workaround, but the modify seams not work, the file:
![image](https://user-images.githubusercontent.com/36035854/154068229-4910a927-c702-4d14-b7f4-6b19376a69e9.png)
the system log:
![image](https://user-images.githubusercontent.com/36035854/154068483-504995ea-3f9e-4a53-a548-a0e9f43afc09.png)

By the way, the buttons like `Enable` ,`Start` and `Stop` do not work at all, I have to enable and start pbr through cli.

![h2qrv-kqcbu.gif](https://s2.loli.net/2022/02/15/mD5zUAleChGgbj8.gif)

I hope this could be solved or is found to be my problem. Thanks for your attention.

**Comment by stangri** [comment]
Thank you for your feedback. While `pbr` has nothing to do with the interface's default routes (and this issue needs to be addressed elsewhere), I could reproduce WebUI buttons not working and I'll look into it.

**Comment by imKnect** [comment]
> Thank you for your feedback. While `pbr` has nothing to do with the interface's default routes (and this issue needs to be addressed elsewhere), I could reproduce WebUI buttons not working and I'll look into it.

I'm not good at networking, but the missing route is surely created by pbr cause it's in the table `CLASH` (which is also create by pbr).
Or there is something I don't understand happend?

**Comment by stangri** [comment]
> > Thank you for your feedback. While `pbr` has nothing to do with the interface's default routes (and this issue needs to be addressed elsewhere), I could reproduce WebUI buttons not working and I'll look into it.
> 
> I'm not good at networking, but the missing route is surely created by pbr cause it's in the table `CLASH` (which is also create by pbr). Or there is something I don't understand happend?

Oh, you're absolutely right. I'm not sure if there's a trigger in OpenWrt for adding a new device. I'll need to sleep on it to think how best to address this scenario.

**Comment by stangri** [comment]
Buttons have been fixed in 0.9.4.-10.

**Comment by imKnect** [comment]
> Buttons have been fixed in 0.9.4.-10.

Thanks for your work!

> > I'm not good at networking, but the missing route is surely created by pbr cause it's in the table `CLASH` (which is also create by pbr). Or there is something I don't understand happend?
> 
> Oh, you're absolutely right. I'm not sure if there's a trigger in OpenWrt for adding a new device. I'll need to sleep on it to think how best to address this scenario.

![image](https://user-images.githubusercontent.com/36035854/154195440-903598b0-9d7a-4402-b050-48ad2420c47d.png)
Actually in this situation (manully binded the tun device to a interface), the disappearance and addition of tun device is related to the trigger of the interface up&down. So I think a little improvement to the interface hotplug script might do the trick.

But in my reproduction process, the interface hotplug script seems not working (edited output but doesn't show up in syslog).

**Comment by stangri** [comment]
I believe a while ago I've changed the `reload` to `restart` as the pbr command in the hotplug script and this should be resolved then. If it isn't please reopen this, I'm sorry it took me so long to respond.
