### ISSUE TITLE
[pbr] Wish: options to allow 'pbr_wan_dst_net' policy on the top or support using a user-define ipset (hash:net, IP-CIDR) as remote address.

### ISSUE THREAD

**Issue by imKnect** [stangri/openwrt_packages#151]
**Relate problem**
![image](https://user-images.githubusercontent.com/36035854/154206784-174c6107-95da-40a1-83be-dcae76fd08ed.png)
I have a policy routing `0-65535` `dst` to my VPN gateway, which I'd like to be the bottom-line. But I also have a lot of IP-CIDRs that need to bypass this VPN gateway, it's a little annoying to manually add a lot of IP-CIDRs to the config.

**Solutions**
Can you provide a option allowing user-script 'pbr_wan_dst_net' policy ('pbr_wan_dst_net', etc) being on the top of the list?
Or can you support using a user-define ipset (hash:net, IP-CIDR) as `dest_addr`?
Both solutions can improve the situation.

BTW, a small bug. Adding IP-CIDR or IP-CIDRs to the `dest_addr` field turns out red alert, fortunately `Save & Apply` works fine.
![image](https://user-images.githubusercontent.com/36035854/154207690-430c9991-e005-4320-999a-ee7624d1c393.png)

**Comment by stangri** [comment]
In the user script you can use `ips` command to create an ipset you need, an `ipt` command to insert the iptables policy targeting this ipset at the top of the chain and then import ipset entries from an external file.

**Comment by imKnect** [comment]
> In the user script you can use `ips` command to create an ipset you need, an `ipt` command to insert the iptables policy targeting this ipset at the top of the chain and then import ipset entries from an external file.

Thank you but is there any docs about what I can do and how to do in the user script? Or I need to find out by myself?

**Comment by stangri** [comment]
It's shell (default OpenWrt shell is `ash`) scripting essentially, so it would be outside of scope of the PBR documentation.

One suggestion on custom scripting for PBR is that you may want to create a policy in PBR settings with one of the known domains from your list to make sure that PBR creates the iptables rule and an ipset for it and then just fill that custom ipset in your script.

**Comment by stangri** [comment]
The current version of `pbr` creates multiple sets (4 sets for ipset and 3 sets for nft set), if something is still missing, please reopen this with details.
