### ISSUE TITLE
[pbr] Wish: `firewall4` compatibility

### ISSUE THREAD

**Issue by maxromanovsky** [stangri/openwrt_packages#152]
I just wanted to track incompatibility of `pbr` with `firewall4`, as per your comment in https://github.com/openwrt/packages/issues/16818#issuecomment-937169645

This would be help enormously those who use openwrt snapshots to decide when to update to the latest build.

**Comment by stangri** [comment]
Additional information available at https://docs.openwrt.melmac.net/pbr/#statement-about-openwrt-22030-release-and-this-package.

The very early version of the `nft`-compatible package is also available in my repo, however the transition is not fully complete and, most importantly, until I can build an nft sets-compatible dnsmasq for my system, I can't properly test it, nor can I advise you use it, if you have any policies with domain names in them.

The nft-sets compatible `dnsmasq` 2.87 might be released very soon. 

If OpenWrt backports `dnsmasq` 2.87 into 22.03 repo, the plan is the following:
1. If `dnsmasq` 2.87 in 22.03 repo still supports ipset, I may merge `pbr-iptables` and `pbr-nftables` into a single package/code called `pbr` again and you could target either netfilter option depending on the `resolver_set` preference with default being the nft.
2.  If `dnsmasq` 2.87 in 22.03 repo no longer supports ipset, the `pbr-iptables` will be renamed `pbr-legacy` and the `pbr-nftables` version will be renamed `pbr`.

I'll try to make the `pbr` available in 22.03 repo.

**Comment by KeyofBlueS** [comment]
dnsmasq 2.87 has been released https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=tag;h=refs/tags/v2.87, now we need to wait for the update in openwrt :+1:

**Comment by stangri** [comment]
Technically, [at the current state](https://docs.openwrt.melmac.net/pbr/#statement-about-openwrt-22030-release-and-this-package), the `pbr` package is firewall4/nft compatible.

**Comment by stangri** [comment]
I'm lacking time to build a dnsmasq-full 2.87 (with nft sets support) for OpenWrt, but current `pbr` should be compatible with the nft sets. As the current version of pbr is fw4/nft-compatible, I'm closing this.
