### ISSUE TITLE
[https-dns-proxy] Firefox canary domain support

### ISSUE THREAD

**Issue by dgcampea** [stangri/openwrt_packages#155]
Since `https-dns-proxy` has a `force_dns` option, should it also support the Firefox canary domain for overriding DoH provider?
For reference, I'm using uci to set a `address=/use-application-dns.net/` option per dnsmasq instance.

Link: https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet

**Comment by stangri** [comment]
@dgcampea thank you for bringing it up. I'll create a similar issue in the upstream package, if it's implemented there, there would be no need for OpenWrt-specific change.

**Comment by stangri** [comment]
Sorry it took a while, I was waiting for the decision on the upstream package.

I've implemented it in this commit: https://github.com/stangri/source.openwrt.melmac.net/commit/ba8717b5e5a37cfa145a065be3170bde4732a9be and if you want to test it out without compiling the package for yourself, you can just copy the init script from https://raw.githubusercontent.com/stangri/source.openwrt.melmac.net/ba8717b5e5a37cfa145a065be3170bde4732a9be/https-dns-proxy/files/https-dns-proxy.init into your live router.

Please let me know if you can/want to test it before I submit a PR for the OpenWrt packages repo.

**Comment by dgcampea** [comment]
I'd use the 'address' directive here instead of 'server'.
https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

**Comment by stangri** [comment]
> I'd use the 'address' directive here instead of 'server'. https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

Why? That same doc you've linked explicitly states that ' --address=/example.com/ is equivalent to --server=/example.com/'. There's already code to backup and restore the `server` entries, why would I want to use `address` instead?

**Comment by dgcampea** [comment]
I was under the impression that if you somehow had an entry for `use-application-dns.net` in /etc/hosts, `--address` would still return NXDOMAIN whereas `--server` would resolve it. Did a quick test, it turns out both have the same behavior (resolve from /etc/hosts).

I usually see `address=` used for domain blacklists and the directive seems more adequate given the context but since it ends up being equivalent I guess there's no harm in using `server=` either.

**Comment by stangri** [comment]
> I usually see `address=` used for domain blacklists and the directive seems more adequate given the context but since it ends up being equivalent I guess there's no harm in using `server=` either.

As a maintainer of `simple-adblock` which uses `server` to get NXDOMAIN for blocked domains, I'm curious to find out which blocklists apps/services use `address` instead.

**Comment by dgcampea** [comment]
> I'm curious to find out which blocklists apps/services use address instead.

I remember seeing some lists that used `address=` but I'm afraid I lost the bookmark for it :(
