### ISSUE TITLE
[simple-adblock] Wish:Update default blocked_domains

### ISSUE THREAD

**Issue by wevsty** [stangri/openwrt_packages#157]
**Is your feature request related to a problem? Please describe.**

Some of the current default subscription blocklist has been explicitly deprecated or not updated for a long time

project url : https://github.com/paulgb/BarbBlock
The project domains list was last updated in 2019. I believe the list is no longer suitable as a default subscription.
```
#	list blocked_domains_url 'https://cdn.jsdelivr.net/gh/paulgb/BarbBlock/blacklists/domain-list.txt'
```

According to disconnect.me, the following addresses have been abandoned and are no longer being updated.
see: https://github.com/disconnectme/disconnect-tracking-protection/issues/171
```
# File size: 4.0K
#	list blocked_domains_url 'https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt'

# File size: 44.0K
#	list blocked_domains_url 'https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt'

# File size: 44.0K
#	list blocked_domains_url 'https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt'
```

**Describe the solution you'd like**

I suggestion is to use another block list for replacement.
For example, using https://github.com/AdguardTeam/cname-trackers
The current size of this list is about 631KB, which I think shouldn't be too much of a problem for modern routers.
```
# github url
list blocked_domains_url 'https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/combined_disguised_trackers_justdomains.txt'

# jsdelivr url
list blocked_domains_url 'https://cdn.jsdelivr.net/gh/AdguardTeam/cname-trackers@master/combined_disguised_trackers_justdomains.txt'
```

**Comment by stangri** [comment]
Thank you! Made it enabled by default in a later commit.
