### ISSUE TITLE
VPN and SQM bypass

### ISSUE THREAD

**Issue by anakinrpi** [stangri/openwrt_packages#159]
I have an openwrt 22.03 in a RP4 with smq enabled. Another rp4 with a wireguard vpn is connected to the openwrt.
When i connect to the vpn i have half limited the speed compared to sqm disabled (I have 100 Mbps down and up, and with sqm I can reach 50 up and down). I couldn't find where is the problem. I want to know if is it possible to bypass in any way the sqm. I think there is no problem with the CPU, the load doest reach 15% with Speedtest and VPN connected. Thanks! And sorry for my bad English.

**Comment by stangri** [comment]
How does this have anything to do with the packages in this repo?
