### ISSUE TITLE
Remove the dependency on package `luci`

### ISSUE THREAD

**Issue by LGA1150** [stangri/openwrt_packages#16]
This commit https://github.com/openwrt/luci/commit/90bf08af829a8e13c3caf6a389bff5212d5204dc introduced a new package named `luci-nginx`, which uses nginx as its web server, while the old `luci` package uses uHTTPd.
With the dependency on `luci`, I can't deselect `uhttpd` despite no need for it.

**Comment by stangri** [comment]
Which package(s) are you including in your build? I'd like you to test a change on a single package before I update all of them.

**Comment by LGA1150** [comment]
w/ `luci-ssl-nginx`
w/o `luci` and `uhttpd`

**Comment by stangri** [comment]
Ok, let's try it another way, which one of **my** packages are you trying to include in your build?

**Comment by LGA1150** [comment]
Any one of them, such as `luci-app-advanced-reboot`

**Comment by stangri** [comment]
Please check `luci-app-advanced-reboot` revision 32 (both binary and source are updated in my repos) and confirm if it works well.

**Comment by LGA1150** [comment]
Compiled with latest master
![image](https://user-images.githubusercontent.com/9155358/42412799-d9c2c53c-8245-11e8-8c8c-6d3d17f21734.png)
Seems to be working, and `uhttpd` isn't included now, thx!

**Comment by stangri** [comment]
Thanks for the report, I'll fix other packages over the weekend!
