### ISSUE TITLE
[pbr] issue with rule generation from cfg

### ISSUE THREAD

**Issue by d3adc0d3** [stangri/openwrt_packages#165]
Seems like there is some issue with nft add rule cmd gen from pbr cfg file. Perhaps missing "ip" prior to daddr?

luci-app-pbr error
![image](https://user-images.githubusercontent.com/79072088/199573441-f12e28d3-292c-458c-a3a4-8fc11ebd0b1c.png)

service restart output
![image](https://user-images.githubusercontent.com/79072088/199574653-8def049e-e064-4c02-981f-a4f72df8569e.png)

Issuing cmd that results in error upon service restart
![image](https://user-images.githubusercontent.com/79072088/199574284-be68244d-8126-4b4d-805b-a8d533c156bf.png)

Tried adding ip prior to daddr
![image](https://user-images.githubusercontent.com/79072088/199574366-4de26145-3b2a-4eb5-8bca-732684b65c0b.png)

**Comment by stangri** [comment]
Please test with `pbr 0.9.9-12` I just pushed to my repo.

This is likely same issue as what I fixed with the protocols, I don't understand why it's happening, I believe I've tested before and `nft` was complaining about duplicates, now it requires them.

**Comment by d3adc0d3** [comment]
That fixed it, thanks.

**Comment by stangri** [comment]
Thanks again for testing/reporting and sorry I forgot to reference the issue in the commit!
