### ISSUE TITLE
[pbr] Issue: No place to file `pbr` issues?

### ISSUE THREAD

**Issue by posita** [stangri/openwrt_packages#178]
`pbr` is not listed here: https://github.com/stangri/source.openwrt.melmac.net/issues/new/choose

As a result, it's unclear where to file `pbr`-related issues.

**Comment by stangri** [comment]
Thanks, fixed in https://github.com/stangri/source.openwrt.melmac.net/commit/4107b437112bc6da68be08cc034b8ccb2e22f494.
