### ISSUE TITLE
[noticed] VPR trying to setup a dormant (tun) iface

### ISSUE THREAD

**Issue by ghost** [stangri/openwrt_packages#19]
0.0.2-16

It seems that VPR is trying to configure a tun iface which is dormant. The iface is present in /etc/config/network but otherwise dormant/dead

`ip a ls tun` or `ip l ls tun`

> Device "tun" does not exist.

and yet VRP is trying to set it up

> err modprobe[]: xt_set is already loaded
> err modprobe[]: ip_set is already loaded
> err modprobe[]: ip_set_hash_ip is already loaded
> notice [9347]: Creating table 'wan/84.[truncated]' [✓]
> notice [9347]: **Creating table 'tun/0.0.0.0' [✗]**
> notice [9347]: Creating table 'wg0/192.168.112.12' [✓]
> notice [9347]: Routing 's5' via wan [✓]
> notice [9347]: Routing 's1' via wan [✓]
> notice [9347]: Routing 'da' via wan [✓]
> notice [9347]: Routing '1750e' via wan [✓]
> notice [9347]: Routing 'dvb-c' via wan [✓]
> notice [9347]: Routing 'stv9s' via wan [✓]
> notice [9347]: Routing 'oc_vpscp' via wan [✓]
> notice [9347]: Routing 'oc_vnc' via wan [✓]
> notice [9347]: Routing 'oc_ssh' via wan [✓]
> notice [9347]: Routing 'lan' via wan [✓]
> notice [9347]: service started on wan/84.[truncated] wg0/192.168.112.12 with errors [✗]
> notice [9347]: **ERROR: Failed to set up 'tun/0.0.0.0'**

**Comment by stangri** [comment]
Check the readme, add the interface to the list of ignored.
