### ISSUE TITLE
[fakeinternet] Issue: cannot find dependency luci-lua-runtime for luci-app-fakeinternet

### ISSUE THREAD

**Issue by echoix** [stangri/openwrt_packages#197]
**Describe the bug**

After reading a bit, it seems that lua was used before, and now apps are written in javascript. Fakeinternet hasn't been transitionned yet 
**Your configs**

<details><summary>Details (empty)</summary>
<p>

1. ```/etc/config/dhcp```

   ```sh

   ```

2. ```/etc/config/network```

   ```sh

   ```

3. ```/etc/config/firewall```

   ```sh

   ```

4. ```/etc/config/fakeinternet```

   ```sh

   ```

</p>
</details> 

**To Reproduce**
1. Follow instructions on https://docs.openwrt.melmac.net/fakeinternet/ and  https://docs.openwrt.melmac.net/#on-your-router

```shell
root@GL-MT1300:~# opkg install fakeinternet luci-app-fakeinternet
Installing fakeinternet (0.1.4-r5) to root...
Downloading https://repo.openwrt.melmac.net/fakeinternet_0.1.4-r5_all.ipk
Installing uhttpd-mod-ubus (2022-10-31-23977554-1) to root...
Downloading https://fw.gl-inet.com/releases/v22.03.4/packages-4.2/mipsel_24kc/packages/uhttpd-mod-ubus_2022-10-31-23977554-1_mipsel_24kc.ipk
Unknown package 'luci-app-fakeinternet'.
Configuring uhttpd-mod-ubus.
Configuring fakeinternet.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lua-runtime for luci-app-fakeinternet
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-fakeinternet found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-fakeinternet.
```

**Expected behavior**
be able to control fakeinternet on at least openwrt22.03 on my GL-Inet device. (mipsel_24kc)

**Fakeinternet run-time information**

<details><summary>Details</summary>
<p>

1. Output of ```/etc/init.d/fakeinternet restart```:

   ```sh

   ```

2. Output of ```iptables-save```:

   ```sh

   ```

</p>
</details>

**Comment by stangri** [comment]
> ```shell
> Downloading https://fw.gl-inet.com/releases/v22.03.4/
> ```

That's a fork of OpenWrt, complain to whoever maintains it or switch to a vanilla/supported OpenWrt.
