### ISSUE TITLE
[pbr] issue: Documentation is stale/does not prominently feature installation for versions >1.1.6-22 for OpenWrt

### ISSUE THREAD

**Issue by posita** [stangri/openwrt_packages#205]
**Describe the bug**

Please update the top post on https://forum.openwrt.org/t/policy-based-routing-pbr-package-discussion/140639/1 and https://docs.openwrt.melmac.net/pbr/#HowToInstall-OpenWrt23.05andnewer to prominently feature a reference to https://docs.openwrt.melmac.net/#OnyourOpenWrtdevicewithopkg for `pbr` installation so that users don't have to dig to understand that a vanilla `opkg update ; opkg install pbr` won't get them the latest version.

**Comment by stangri** [comment]
wrong repository, there's no README here.

**Comment by posita** [comment]
> wrong repository, there's no README here.

What's the right repository then?
