### ISSUE TITLE
[VPR bug] adding WG iface sends router into reboot loop (kernel panic) when SQM instance enabled on the wg iface

### ISSUE THREAD

**Issue by ghost** [stangri/openwrt_packages#24]
TOS 3.10.3 ({"kernel":"4.4.138-1e8e1b4c23f383e990eb3c4f490f5f2e-1","hostname":"router","system":"ARMv7 Processor rev 1 (v7l)","model":"Turris Omnia","release":{"distribution":"OpenWrt","version":"Chaos Calmer","revision":"r47055","codename":"omnia","target":"mvebu/generic","description":"OpenWrt omnia 15.05"}})

---
After having updated to 0.0.2-22 and applied some VPR settings the router went into a reboot loop, rebooting every few minutes.
Even disabling VPR between reboots did not solve it.

Had to rollback the router (0.0.2-21) and since then the reboots have ceased.

Since the systemlog is rolled over at each reboot it was not possible to gather information of how VPR exactly causes the reboots.

**Comment by stangri** [comment]
Wow, this has completely taken me by surprise. See if 0.0.2-23 helps.

You can actually capture the log. Before upgrading to the new version set enabled=0, then upgrade, then (either thru WebUI or manually) set enabled=1 and start the service **while** having another ssh session to the router and doing ```tail -f <system_log_gile```.

Also, before you upgrade probably, can you run the ```/etc/init.d/vpn-policy-routing support -p```? If it complains about missing dependencies, install them to make sure the paste is uploaded.

**Comment by ghost** [comment]
Well, it been a little surpise indeed.

> ERROR: curl, libopenssl or ca-bundle were not found!
> Run 'opkg update; opkg install curl libopenssl ca-bundle' to install them.

`curl` and `libopenssl` are present whilst `ca-bundle` is not as not being provided by the TO repo (sigh)...

The [TO team been made aware of it](https://forum.turris.cz/t/location-of-ca-certificate-bundle-file/7548) since it is needed for TLS authentication of the unbound resolver but apparently they cannot be bothered.

Out of desperation I got `/etc/ssl/certs/tls-ca-bundle.pem` from one of my linux boxes...

TO repo currently only provides `ca-certificates` which is a bunch of _single_ root certificates and which perhaps could be converted to a bundle with `cat /etc/ssl/certs/* > /etc/ssl/certs/ca-bundle.pem`. 

Suppose I should not install 0.0.2-23 without `ca-bundle`?

**Comment by stangri** [comment]
Uhm, if you could just capture the output of ```/etc/init.d/vpn-policy-routing support``` before upgrade and e-mail it to me if 0.0.2-23 fails, that'd also work.

And try to capture the log of running 0.0.2-23 thru ```tail -f``` in another ssh session.

**Comment by ghost** [comment]
Unfortunately that did not fix it, still rebooting in a loop...

Seems that whatever is causing it been introduced prior 0.0.2-21 already because after the rollback I repeated the step with the same outcome (reboot loop).

I kept on testing new releases for #10 and thus the steps were adding a lan segment to be routed trough a WG iface.

Just to be clear the reboot loop does not occur after the update but only after the previous step and pressing `save & apply`

Now I tried the same steps with 0.0.2-21 except adding the lan segment to WAN instead and _no_ reboot loop after pressing `save & apply`!

From that point made the upgrade to 0.0.2-23 and then changed the aforementioned lan segment from WAN to WG and pressed `save & apply` and _bang_ the rebooting loop starts all over again.

The last documented testing on #10 was with 0.0.2-11 but I reckon that I might have checked also in between 2-11 and 2-20, just cannot recall which was the last.

It seems that whenever the WG iface gets active/online and picked up by VPR the reboot is initiated.

Still need the output from `/etc/init.d/vpn-policy-routing support`?

**Comment by ghost** [comment]
Not that I expected it to be related to luci-app-vpn-policy-routing I gave a it try nonetheless after having updated to luci-app-vpn-policy-routing/stangri_repo/git-18.212.55585-176e246-32, just for good measure.

It did not remedy the issue however.

Do you reckon this being another TO specific issue, or rather something WG specific?

**Comment by ghost** [comment]
updated to vpn-policy-routing 0.0.2-2**3** | luci-app-vpn-policy-routing git-18.220.31345-7609919-32 but the issue is still present

**Comment by ghost** [comment]
meantime upgraded to

- TOS  3.10.**4** {"kernel":"4.4.**147**-0a333a8e606ab056173befac424900d2-1","hostname":"router","system":"ARMv7 Processor rev 1 (v7l)","model":"Turris Omnia","release":{"distribution":"OpenWrt","version":"Chaos Calmer","revision":"r47055","codename":"omnia","target":"mvebu\/generic","description":"OpenWrt omnia 15.05"}}
- vpn-policy-routing  0.0.2-2**4**
- luci-app-vpn-policy-routing git-18.225.48207-809d3b9-33

the issue is presistent and when monitoring the system log there is no print out as to the cause of the reboot

**Comment by ghost** [comment]
migrated to

- vpn-policy-routing 0.0.2-2**5**
- {"kernel":"4.4.**150**-0a333a8e606ab056173befac424900d2-1","hostname":"router","system":"ARMv7 Processor rev 1 (v7l)","model":"Turris Omnia","release":{"distribution":"OpenWrt","version":"Chaos Calmer","revision":"r47055","codename":"omnia","target":"mvebu\/generic","description":"OpenWrt omnia 15.05"}}
- TOS 3.10.**5**

---
the issue is presistent but for the first time now **got a log print out!**

> [88410.513258] Unable to handle kernel NULL pointer dereference at virtual address 00000002
> alert kernel[]: [88410.521389] pgd = ea118000

**Comment by ghost** [comment]
migrated to vpn-policy-routing 0.0.2-2**8** with the issue persistent, the log showing:

> alert kernel[]: [1071442.984542] Unable to handle kernel paging request at virtual address 40a5f134
> alert kernel[]: [1071442.991974] pgd = ecbc4000
> alert kernel[]: [1071442.994877] [40a5f134] *pgd=00000000
> emerg kernel[]: [1071442.998655] Internal error: Oops: 5 [#1] SMP ARM

**Comment by ghost** [comment]
migrated to

- {"kernel":"4.4.**156**-0a333a8e606ab056173befac424900d2-1","hostname":"router","system":"ARMv7 Processor rev 1 (v7l)","model":"Turris Omnia","release":{"distribution":"OpenWrt","version":"Chaos Calmer","revision":"r47055","codename":"omnia","target":"mvebu\/generic","description":"OpenWrt omnia 15.05"}}
-  TOS 3.10.**6**
- kmod-wireguard 	4.4.156+0.0.20180910-..2-1

---
issue persistent, the log showing:

> alert kernel[]: [ 4591.684808] Unable to handle kernel paging request at virtual address 312f736d
> alert kernel[]: [ 4591.692084] pgd = ea5a4000
> alert kernel[]: [ 4591.694796] [312f736d] *pgd=00000000
> emerg kernel[]: [ 4591.698432] Internal error: Oops: 5 [#1] SMP ARM

**Comment by ghost** [comment]
migrated to

- {"kernel":"4.4.**161**-0a333a8e606ab056173befac424900d2-1","hostname":"router","system":"ARMv7 Processor rev 1 (v7l)","model":"Turris Omnia","release":{"distribution":"OpenWrt","version":"Chaos Calmer","revision":"r47055","codename":"omnia","target":"mvebu/generic","description":"OpenWrt omnia 15.05"}}
- TOS 3.10.**8**
- kmod-wireguard 4.4.161+0.0.2018**0918**-..2-1

with the issue still present

**Comment by ghost** [comment]
@stangri 

Just discovered what is apparently the culprit for the kernel panic - a potential conflict with a `SQM` instance enabled on the `wg iface`

```
config queue
	option debug_logging '0'
	option qdisc 'fq_codel'
	option enabled '1'
	option interface 'wg0'
	option download '90000'
	option upload '19000'
	option verbosity '0'
	option qdisc_advanced '0'
	option script 'piece_of_cake.qos'
	option linklayer 'none'
```

**Comment by stangri** [comment]
Could you please confirm if you have VPR working with the WG interface?

**Comment by ghost** [comment]
- SQM enabled on WAN and disabled on WG then it is working.
- Enabling SQM on WG and starting VPR causes the kernel panic.

I am not sure whether it makes sense to have SQM enabled on WAN and WG but for now it remains disabled on WG to prevent said kernel panic with VPR

**Comment by stangri** [comment]
Are you using the SQM package from Turris or OpenWrt repo? There might be collisions on packet masking which can be resolved with proper settings.

**Comment by ghost** [comment]
from the TO repo 

sqm-scripts 	1.0.7-3
sqm-scripts-extra 	2016-06-08-1

I would not know how to debug the potential collisions.

**Comment by stangri** [comment]
I asked because I'm not aware how they're building packages for their repo.
They use the same mask as the mainline OpenWrt SQM (0x0000ff), which shouldn't conflict with what VPR uses (0xff0000). I'm at loss what's causing the kernel panic.
@tohojo -- do you have any idea why enabling SQM on a wireguard tunnel and starting VPR can cause the kernel panic?

**Comment by tohojo** [comment]
Might be because running SQM re-enables a qdisc on the interface, and wg expects to run in queue-less mode?

Why are you running SQM on the wg interface instead of the underlying physical interface?

**Comment by ghost** [comment]
@tohojo 

SQM is running on WAN interface, which is supposedly the underlying interface for WG. But I was not sure whether SQM on the WAN would also deal with the packages on the WG interface and thus enabled it there as well. 

Having said that SQM enabled on both interfaces, WAN and WG, does works without VPR enabled. Starting VPR in this setting is causing the kernel panic however with this error reported by the kernel

> Unable to handle kernel paging request at virtual address

**Comment by tohojo** [comment]
Ah, scrolled up some more now.

Don't have a good explanation for the crash; but with the current structure of wireguard, you won't get much benefit from running sqm on the wg interface, so a solution for now could be to just not do that? :)

**Comment by ghost** [comment]
> so a solution for now could be to just not do that?

Yep, that is what I concluded and implemented. At least I was able to figure out the cause since it was driving me nuts and rendering VPR unusable.

**Comment by ghost** [comment]
so v031 fixed this then? Enabled SQM on WG and restarted VPR and no more crash :+1: :smiley:
