### ISSUE TITLE
wwan interface is not detected

### ISSUE THREAD

**Issue by Smoffitz** [stangri/openwrt_packages#3]
I'm trying to move from vpnbypass which correctly identified my wwan interface, but it seems this project doesn't detect wwan as a wan interface

**Comment by stangri** [comment]
Which project?

**Comment by Smoffitz** [comment]
Sorry, didn't realize this was a mult-project repo.  I'm trying to switch from vpnbypass to vpn-policy-routing but vpn-policy-routing doesn't seems to support my wwan interface.

**Comment by stangri** [comment]
I assume you've checked out the project README?

**Comment by Smoffitz** [comment]
I have checked out the README, is there something in there that I missed or should read more closely?

**Comment by stangri** [comment]
It has explicit instructions on what to do if things are not working.
