### ISSUE TITLE
[VPR] installed dependencies not detected

### ISSUE THREAD

**Issue by ghost** [stangri/openwrt_packages#30]
{"kernel":"4.4.150-0a333a8e606ab056173befac424900d2-1","hostname":"router","system":"ARMv7 Processor rev 1 (v7l)","model":"Turris Omnia","release":{"distribution":"OpenWrt","version":"Chaos Calmer","revision":"r47055","codename":"omnia","target":"mvebu\/generic","description":"OpenWrt omnia 15.05"}}

---
`/etc/init.d/vpn-policy-routing support -p`

> vpn-policy-routing 0.0.2-25 running on OpenWrt Chaos Calmer. WAN (IPv4): wan/dev/
> 
> Dnsmasq version 2.78  Copyright (c) 2000-2017 Simon Kelley
> Compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify
> 
> **ERROR: curl, libopenssl or ca-bundle were not found!**
> Run 'opkg update; opkg install curl libopenssl ca-bundle' to install them.

`opkg update; opkg install curl libopenssl ca-bundle`

> Package curl (7.60.0-1) installed in root is up to date.
> Package libopenssl (1.0.2o-1) installed in root is up to date.
> Package ca-bundle (20180409-2) installed in root is up to date.

**Comment by stangri** [comment]
Thank you for the report. Fixed in `vpn-policy-routing 0.0.2-26`.

**Comment by n8v8R** [comment]
Is that version already available?

`opkg search '*vpn-policy-routing*'`

> luci-app-vpn-policy-routing - git-18.232.74480-b93d3f3-33
> vpn-policy-routing - 0.0.2-25
