### ISSUE TITLE
[VPR] Suppress `module is already loaded` warnings in system log

### ISSUE THREAD

**Issue by LGA1150** [stangri/openwrt_packages#31]
https://github.com/stangri/openwrt_packages/blob/fe4541878e502b6088252538abef01218ac03591/vpn-policy-routing/files/vpn-policy-routing.init#L526

This line of code doesn't suppress the `module is already loaded` warning messages in system log.
I have to add `2>/dev/null` at the end of each `modprobe` command to completely suppress them.
```
modprobe xt_set 2>/dev/null
modprobe ip_set 2>/dev/null
modprobe ip_set_hash_ip 2>/dev/null
```
Or you can make some error handling by checking exit code (`modprobe` returns `255` if it can't find/load the module, returns `0` if it loads the module or already loaded):
```
modprobe xt_set 2>/dev/null &&
modprobe ip_set 2>/dev/null &&
modprobe ip_set_hash_ip 2>/dev/null ||
echo "failed to load module"
```

**Comment by stangri** [comment]
Can't reproduce fix as working.
