### ISSUE TITLE
luci-app-advanced-reboot

### ISSUE THREAD

**Issue by celticnestor** [stangri/openwrt_packages#40]

**Comment by celticnestor** [comment]
Hi @stangri,

Appreciate the hard work on packages that really make a difference!

I am running luci-app-advanced-reboot on Lede SNAPSHOT r8466-251c350727 / LuCI Master (git-18.320.75602-93fdac8), a Davidc502 LEDE Snapshot.

When taking action "Reboot to alternative partition..." I am getting following error message:
`Failed to execute call dispatcher target for entry '/admin/system/advanced_reboot/alternative_reboot'.
The called action terminated with an exception:
/usr/lib/lua/luci/controller/advanced_reboot.lua:124: attempt to concatenate global 'errorMessage' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/advanced_reboot.lua:124: in function </usr/lib/lua/luci/controller/advanced_reboot.lua:97>
	(tail call): ?`

Is there anything I can do to help debug this issue?
Is there an alternative command to force the router boot from the other partition?

Thx for your help!

**Comment by stangri** [comment]
```I am running luci-app-advanced-reboot on Lede SNAPSHOT r8466-251c350727 / LuCI Master (git-18.320.75602-93fdac8), a Davidc502 LEDE Snapshot.``` -- on which device?
Try build 034 however the fact that that part of code was called is indicative that your device is not supported.

**Comment by celticnestor** [comment]
Silly me.... device is Linksys WRT3200ACM-RM2, should be supported.

Apologies for the basic q: where can I get a build 034? I am unclear on how to relate that to Davidc snapshots...

Thx again!

**Comment by stangri** [comment]
As far as I understand, all flavours of WRT3200 family are supported. Check the repo README for instructions.

**Comment by celticnestor** [comment]
Hi @stangri , thx for your response.

My point is: why am I getting this error message (on the top of the thread) if this router is supported?
I reverted back to the stock FW and back to LeDE and the problem did not go away... if you could have a look to the error message and comment if there is a way to solve it I would be grateful.

**Comment by stangri** [comment]
Which version of the advanced reboot app are you running?

**Comment by celticnestor** [comment]
luci-app-advanced-reboot   git-18.320.75602-93fdac8-33

**Comment by celticnestor** [comment]
@stangri Any comments on this?

**Comment by stangri** [comment]
Please update to latest version.

**Comment by celticnestor** [comment]
Hi @stangri 

Upgraded to luci-app-advanced-reboot git-19.011.54860-47d9205-33 and the issue continues to be there. This is the error message I am getting now:

> Failed to execute call dispatcher target for entry '/admin/system/advanced_reboot/alternative_reboot'.
> The called action terminated with an exception:
> /usr/lib/lua/luci/controller/advanced_reboot.lua:124: attempt to concatenate global 'errorMessage' (a nil value)
>stack traceback:
>	/usr/lib/lua/luci/controller/advanced_reboot.lua:124: in function
</usr/lib/lua/luci/controller/advanced_reboot.lua:97>
>	(tail call): ?

Anything I can do to recover this functionality? THX!

**Comment by stangri** [comment]
Latest version should have -37 at the end of the version string.
