### ISSUE TITLE
[VPR] no WG traffic with kernel reverse-path strict filter enabled

### ISSUE THREAD

**Issue by ghost** [stangri/openwrt_packages#41]
- TOS  3.11
{"kernel":"4.4.165-4a7a81f8db0ad743e54c68e1845c60b6-1","hostname":"router","system":"ARMv7 Processor rev 1 (v7l)","model":"Turris Omnia","release":{"distribution":"OpenWrt","version":"Chaos Calmer","revision":"r47055","codename":"omnia","target":"mvebu\/generic","description":"OpenWrt omnia 15.05"}}
- VPR 0.0.2-31 / 0.0.2-32
- WG 0.0.20181119

---
enabling kernel reverse-path filter via sysctl

```
net.ipv4.conf.default.rp_filter=1
net.ipv4.conf.all.rp_filter=1
```

ceases the VPR routed traffic on the WG iface. Instead packages showing up as Martians.

**Comment by stangri** [comment]
I'm guessing some of the kernel modules required by VPR are incompatible with RP-path filter.

As I do not currently have the WG set up, it may take me a while to test this on 18.06.1.

**Comment by ghost** [comment]
Sure, no worries. Happy season! :mrs_claus:

**Comment by ghost** [comment]
setting `rp_filter = 2` solves the matter.

> 2 - Loose mode as defined in RFC3704 Loose Reverse Path
>     Each incoming packet's source address is also tested against the FIB
>     and if the source address is not reachable via any interface
>     the packet check will fail.
> Current recommended practice in RFC3704 is to enable strict mode
> to prevent IP spoofing from DDos attacks. **If using asymmetric routing
> or other complicated routing, then loose mode is recommended.**
