### ISSUE TITLE
[vpn-policy-routing] Wish: Virtual Routing and Forwarding (VRF) support

### ISSUE THREAD

**Issue by ghost** [stangri/openwrt_packages#45]
Whilst reading on https://www.kernel.org/doc/Documentation/networking/vrf.txt 

> The design also allows the use of higher priority ip rules (Policy Based Routing, PBR)

it occurred to me that it could potentially make sense for VPR to use and thus be liberated of any nf/ipt/nft/ipset bloating/complications? Even running a VPN server/client in a lxc container routing via/to/from via such container https://github.com/stangri/openwrt_packages/issues/28 sounds feasible? And not to mention being liberated from `uci` with its curious naming convention for network bridges , https://github.com/stangri/openwrt_packages/issues/42#issuecomment-451622804

**Comment by stangri** [comment]
I see that VRF support has been added to OpenWrt: https://github.com/torvalds/linux/blob/master/drivers/net/Kconfig#L430 however I'm not sure if it's enabled/supported by default or needs a specially built kernel. Have you tested the VRF support in OpenWrt?

**Comment by stangri** [comment]
Closing due to lack of reply.
