### ISSUE TITLE
advanced-reboot typo in Makefile

### ISSUE THREAD

**Issue by LGA1150** [stangri/openwrt_packages#46]
https://github.com/stangri/openwrt_packages/blob/da75d0209a483fd50687ab5d37e17a1adb26f233/luci-app-advanced-reboot/Makefile#L11 "altnerative"

**Comment by stangri** [comment]
Thank you for the report, fixed in ```luci-app-advanced-reboot_git-19.006.40074-a98e239-35_all.ipk```.
