### ISSUE TITLE
[vpn-policy-routing] Wish: TOR routing

### ISSUE THREAD

**Issue by ghost** [stangri/openwrt_packages#47]
Whilst the readme is bare of any hint about tor routing the init script code though has some related snippets on display and thus wondering whether/how routing via tor might work, considering tor is not providing an iface but a SOCKET5 proxy?

I am currently running a tor client node with username/password credentials and would like to route `onion.` centrally from the router rather than with a proxy browser plugin for each client.
One other issue comes to mind - resolving tor domains, which currently is set in the browser plugin with `Send DNS through SOCKS5 proxy`
I am also looking whether that DNS can be handled centrally by the router's DNS server (`unbound`) but have not reached a solution yet.

**Comment by stangri** [comment]
The Tor support is planned but not at all implemented. Whatever code is there is just a stub, so that if anyone wants to contribute, they can.

**Comment by y-alexey** [comment]
Tor routing can be easily realized by port forwarding to 127.0.0.1:9040 in fw3. You just need criteria or ready ipset sets of tragets.
It's already work for me.

And I try to find ability to forward the same manner to VPN tunnel. Can't find how to point existing ipset in policy-routing rules.

**Comment by stangri** [comment]
> Tor routing can be easily realized by port forwarding to 127.0.0.1:9040 in fw3. You just need criteria or ready ipset sets of tragets.
> It's already work for me.

Do you mind sharing the iptables/fw3 entries you have to make VPR work with the TOR tunnel?

**Comment by stangri** [comment]
Are you still willing to test this out? I've made some steps towards TOR support in recent builds.

**Comment by h4de5** [comment]
@stangri I am here to test this.

my setup:
i installed tor and privoxy using this guide: https://www.lan-monitor.de/openwrt-tor-proxy-einrichten/

using an additional PAC file, the proxy is picked up automatically in windows.
still, some devices ignore those proxy settings. for them i would like to force them through a (currently not existing) tor interface.

let me know if I can help.

**Comment by stangri** [comment]
> @stangri I am here to test this.
> 
> my setup:
> i installed tor and privoxy using this guide: https://www.lan-monitor.de/openwrt-tor-proxy-einrichten/
> 
> using an additional PAC file, the proxy is picked up automatically in windows.
> still, some devices ignore those proxy settings. for them i would like to force them through a (currently not existing) tor interface.
> 
> let me know if I can help.

Installing a package from my repo would be a great start. 👍

**Comment by h4de5** [comment]
Ok. Forgot to mention that: a private openvpn interface and the vpn-policy-routing extension is up and running without problems since ages ;)

**Comment by stangri** [comment]
Should be working in 0.3 versions and up. Please reopen if it doesn't.

**Comment by h4de5** [comment]
@stangri  can you provide on how to do this?
my web proxy is listening on 8118 and forwards requests to the tor client on port 9050.

this is what vpr shows - in the interface dropdown I only got WAN and openvpn
![image](https://user-images.githubusercontent.com/6115324/108777247-cd35cf80-7563-11eb-9ff6-9a2b36023859.png)

**Comment by ilshatms** [comment]
> Are you still willing to test this out? I've made some steps towards TOR support in recent builds.

@stangri Hey
still relevant? I use vpr version 0.3.4-8, I don't see support TOR

**Comment by stangri** [comment]
> > Are you still willing to test this out? I've made some steps towards TOR support in recent builds.
> 
> @stangri Hey
> still relevant? I use vpr version 0.3.4-8, I don't see support TOR

How did you check the tor support?

**Comment by h4de5** [comment]
maybe we got a different understanding on that feature. i would expect that a Tor i entry is showing up in the drop down next to where i can select the interface in each rule row. if it is supported differently i did not find out how yet.

**Comment by ilshatms** [comment]
> How did you check the tor support?

@stangri,

I see the TOR interface, but when setting up policies by domain or port, I see service errors.


<img width="630" alt="Снимок экрана 2021-11-14 в 12 18 41" src="https://user-images.githubusercontent.com/17129298/141675037-b7ee617a-1b50-4f01-8324-767616a53ae5.png">
<img width="740" alt="Снимок экрана 2021-11-14 в 12 18 56" src="https://user-images.githubusercontent.com/17129298/141675039-4c9f730b-c47d-4d1e-aa38-957ca1fd31ae.png">
