### ISSUE TITLE
[VPR question] routing outbound traffic from local lxc guest via host's VPN

### ISSUE THREAD

**Issue by ghost** [stangri/openwrt_packages#48]
TOS 3.11.2 RC | vpn-policy-routing 0.0.2-35 | luci-app-vpn-policy-routing 	git-19.006.40074

{"kernel":"4.4.169-7bc33afbb1b35f5830b2b1b42c9cd8a0-2","hostname":"router","system":"ARMv7 Processor rev 1 (v7l)","model":"Turris Omnia","release":{"distribution":"OpenWrt","version":"Chaos Calmer","revision":"r47055","codename":"omnia","target":"mvebu\/generic","description":"OpenWrt omnia 15.05"}}
___

I have a got a few lxc guests on the router (host) with ip subnets (l3 dev bridge) different from the router (host) and I would consider each such lxc guest being just another lan client to the router.

With the below conf I would expect ingress to 10.169.112.0/24 via nc and egress from 10.169.112.0/24 via wg.
However, once activated 10.169.112.0/24 becomes inaccessible and I am bothering you because apparently I cannot see why this happening.

Not sure if I got my routing logic mixed up?
___

```
config policy
	option remote_addresses '10.169.112.0/24'
	option interface 'nc'
	option name 'router-nc-ingress'

config policy
	option name 'router-nc-egress'
	option local_addresses '10.169.112.0/24'
	option interface 'wg0'

config policy
	option name 'lan'
	option local_addresses '192.168.112.12/24'
	option interface 'wg0'

config vpn-policy-routing 'config'
	option verbosity '2'
	option ipv6_enabled '0'
	option ipset_enabled '1'
	option dnsmasq_enabled '0'
	option strict_enforcement '1'
	list ignored_interface 'guest'
	option udp_proto_enabled '1'
	list supported_interface 'nc'
	option enabled '1'
```

**Comment by stangri** [comment]
I have a feeling you're way ahead of me in the knowledge on routing and containers and routing from containers, so as much as I wish to help, I don't think I can.
