### ISSUE TITLE
ERROR: service failed to load kernel modules

### ISSUE THREAD

**Issue by AlexanderSch90** [stangri/openwrt_packages#51]
I have the follwing Error since i update vpn-poliy-routing: 
user.notice vpn-policy-routing [1789]: ERROR: service failed to load kernel modules!

I have Chaos Calmer 15.05.1 r49389

How can i rollback to an earlier Version?

**Comment by stangri** [comment]
Which version of VPR do you have?

**Comment by AlexanderSch90** [comment]
Sorry. It was: 0.0.2-36

I made a upgrade from 0.0.1-7b17 

Kernel-Version: 3.18.44

**Comment by stangri** [comment]
Please try the -37 build from my repo.

**Comment by AlexanderSch90** [comment]
its working 
Thanks!
