### ISSUE TITLE
After enabling, all connections, randomly, either go through WAN or not routed at all.

### ISSUE THREAD

**Issue by randomsymbols** [stangri/openwrt_packages#54]
OpenWrt 18.06.1 r7258-5eb055306f / LuCI openwrt-18.06 branch (git-18.228.31946-f64b152) 

WireGuard

Installed according to the manual, all dep met. 

All connections, randomly, either go through WAN or not routed at all.

**Comment by TheHellSite** [comment]
I am experiencing a similar behaviour!
Once I enable/start OPBR, my whole network goes a bit crazy. Even when there are no rules set. Network clients seem to have trouble accessing internet websites or services like netflix. 
I have to stop and disable OBPR, and then reboot my router.

This is my issue:
https://forum.openwrt.org/t/transmission-opbr/33390/8

**Comment by stangri** [comment]
Running Wireguard. Cannot reproduce.
