### ISSUE TITLE
[VPR feature suggestion] Rule Enable/Disable Option

### ISSUE THREAD

**Issue by simonbytes** [stangri/openwrt_packages#57]
It would be handy to add an Enable option to rules in the list. Like in openwrt firewall rules list.

The policy section in this image of your openwrt_package shows it does only give the possibility to delete a rule to temporarily disable it. Even a moved rule would be readed obviosly.
![Image of current VPR rule list](https://raw.githubusercontent.com/stangri/openwrt_packages/master/screenshots/vpn-policy-routing/screenshot03-basic.png)

**Comment by ghost** [comment]
dup https://github.com/stangri/openwrt_packages/issues/38

**Comment by simonbytes** [comment]
Well, if the width of the luci screen is important, I will try to look for an alternate way to make disabling a rule possible and report back.

**Comment by stangri** [comment]
@simonbytes implemented in vpn-policy-routing 0.0.7-5 and luci-app-vpn-policy-routing 44. Check the README for more info.
