### ISSUE TITLE
[FEATURE] LuCi: Start service without enabling startup at system start

### ISSUE THREAD

**Issue by TheHellSite** [stangri/openwrt_packages#58]
Whenever I start the service from its LuCi page, it always enables the automatic startup at system start.
Can you please change it so it just starts the service without changing the system start setting for it?
I know it is, right now, intended this way. But I think if someone needs it at system start, they can just set this in the startup page of LuCi.

**Comment by stangri** [comment]
Or you can start the service and disable boot start.
