### ISSUE TITLE
[BUG] Enabling VPR messes with internet access

### ISSUE THREAD

**Issue by TheHellSite** [stangri/openwrt_packages#59]
I am running vpn-policy-routing "0.0.4-4" on OpenWrt "18.06.2 r7676-cddd7b4c77 / LuCI openwrt-18.06 branch (git-19.020.41695-6f6641d)".

Even after deleting all rules in vpr, clients of my LAN go crazy once I start vpr.
My fire tv stick can't use netflix anymore, PCs fail to connect to websites, ....

Please tell me, what you need for troubleshooting.

**Comment by stangri** [comment]
Cannot reproduce.
