### ISSUE TITLE
Q - Bypass VPN for interfaces like virbr0

### ISSUE THREAD

**Issue by Strykar** [stangri/openwrt_packages#60]
Is it currently possible to bypass VPN for traffic originating from an interface? I run KVM guests that NAT via a separate interface like virbr0 and do not want any of the VMs to go via the VPN.

**Comment by stangri** [comment]
Better to post questions like that in the forum, where they will stay visible after being addressed.

No, not possible with vpnbypass, I'm working on adding this to vpn-policy-routing package tho.
