### ISSUE TITLE
luci-app-vpn-policy-routing page load error

### ISSUE THREAD

**Issue by sages** [stangri/openwrt_packages#63]
Running latest snapshot build on ath79 wr842n-v3
Get the following error on the VPR luci page.

`Failed to execute cbi dispatcher target for entry '/admin/services/vpn-policy-routing'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/vpn-policy-routing.lua:98: attempt to concatenate local 'tmpfsVersion' (a nil value)
stack traceback:
	/usr/lib/lua/luci/model/cbi/vpn-policy-routing.lua:98: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:866: in function </usr/lib/lua/luci/dispatcher.lua:860>`

luci-app-vpn-policy-routing - git-19.115.41336-35ace20-40
vpn-policy-routing - 0.0.5-0
OpenWrt SNAPSHOT, r9911-fdf1aae77d

**Comment by stangri** [comment]
Thank you for the report, fixed in git-19.120.24458-1b79446-41.

**Comment by sages** [comment]
Installed update and appears to be working ok.
