### ISSUE TITLE
[luci-app-vpn-policy-routing] columns too wide

### ISSUE THREAD

**Issue by ghost** [stangri/openwrt_packages#69]
* 19.07
*  luci-app-vpn-policy-routing git-19.204.23774-bd44189-44
____

Columns for Protocol | Chain | Iface are spread too wide

![Annotation 2019-07-25 091235](https://user-images.githubusercontent.com/13611490/61853567-7fa33d80-aebc-11e9-97ae-02c34eea4580.png)

**Comment by stangri** [comment]
AFAIK, this is auto-set by Luci, I have no control over this.

**Comment by ghost** [comment]
from the cross referenced upstream issue tracker

> There is no such app in this repo, please clarify your issues with the developer directly. If you're are not satisfied with the measurements of the default templates, you can change nearly every aspect of your app design with a bit of customization of these.

**Comment by ghost** [comment]
appears to be a bug in the material theme https://github.com/openwrt/luci/issues/2927
