### ISSUE TITLE
vpn-policy-routing - support for router with wwan interface

### ISSUE THREAD

**Issue by ivlovric** [stangri/openwrt_packages#73]
Hi,

I am using Pandorabox on Xiaomi MI router with vpn-policy-routing 0.1.0-6 but I am not able to access anything on internet for devices defined in my policies.
I suspect it is because I use WWAN interface to access internet and not standard WAN or WAN6.

Please find all logs as README file suggested attached
[vpn-policy-routing.txt](https://github.com/stangri/openwrt_packages/files/3535875/vpn-policy-routing.txt)

Also, I commented out lines from init script checking for kernel modules that are loaded but check fails regardless
               _

> if [ "$modprobeStatus" -gt 0 ] && ! is_chaos_calmer; then
>                        output "$_ERROR_: $serviceName failed to load kernel modules!\\n"
>                        tmpfs 'set' "Fail: $serviceName failed to load kernel modules!"
>                        return 1
>                fi

_  

Thanks,
I

**Comment by stangri** [comment]
All your policies are disabled. Not a bug.
