### ISSUE TITLE
[VPR BUG] Multiple instances of OVPN binds incorrect DNS settings from other TUNs

### ISSUE THREAD

**Issue by BlowflyOZ** [stangri/openwrt_packages#79]
Hi, I'm running Operwrt 18.06.4 with 3 instances (3 tun interfaces) of Openvpn client. Each instance is directed through an ExpressVPN connection to US, CA and UK. Policy based routing (v 0.1.1-1) then allows for easy toggling of many devices to different Tunnels simultaneously.  

My setup works great with one tunnel running, but starting two or more creates some very strange issues with DNS leak tests showing each tunnel to be using a pushed DNS server configuration from either of the other running tunnels, rendering each tunnel very leaky. 

The issue is further compounded when all tunnels are then stopped and the test device is adjusted to use the WAN instead of tun. Even though all OVPN services are no longer running, the pushed DNS server setting from the previous tunnel connection follows  the device even after its policy has been moved to WAN. Only a network restart reverts things back to the correct local DNS servers.

Restarting the network whilst multiple OVPN tunnels are running seems to break the whole thing, with tunnels remaining active but no routing through them being possible after the restart. I have to restart ovpn to bring tunnels back.  

Lastly, toggling any device between VPN instances moves the device to each new tun correctly, but the pushed DNS settings don't move with it. 

I've tried many tests with dnsmasq IPset and defualt ipset, all give the same result.

Happy to help test VPR further , its a great piece of code

**Comment by stangri** [comment]
VPR does not modify DNS settings in any way, not a VPR issue.
