### ISSUE TITLE
[feature request] route icmp inside wireguard tunnel

### ISSUE THREAD

**Issue by ghost** [stangri/openwrt_packages#8]
0.0.1-25

It appears that icmp traffic is routed outside the PBR assigned vpn tunnel, at least ovpn tun (did not test others). Which can be a bit confusing if debugging with tracert from a Win box as the OS is utilizing icmp for `tracert`, and `ping` naturally.

**Comment by stangri** [comment]
I think I've implemented a setting for that, do you mean it doesn't work with the specific interface set as ICMP interface?

**Comment by ghost** [comment]
Yup, I saw something in the Advanced Settings recently but did not get around testing it yet, it was not there in 0.0.1-25 anyway.

However, the ICMP option seems to have vanished from luci-app-vpn-policy-routing git-18.193.61091-777f..-28

**Comment by stangri** [comment]
Still there, just underneath OUTPUT chain setting.

**Comment by ghost** [comment]
Oh yeah, it shows once the OUTPUT Chain gets enabled. Will test it when I got the WG connectivity issue sorted. Closing for now.

**Comment by ghost** [comment]
Enabled `Create OUTPUT Chain` and set the `Default ICMP Interface` to the VPN iface. Ran `traceroute` from the router as well as from router clients (win/android) and all went through WAN only.

---
luci-app-vpn-policy-routing | git-18.194.53747-b383..-29
vpn-policy-routing | 0.0.2-17

TOS 3.10.3 ({"kernel":"4.4.138-1e8e1b4c23f383e990eb3c4f490f5f2e-1","hostname":"router","system":"ARMv7 Processor rev 1 (v7l)","model":"Turris Omnia","release":{"distribution":"OpenWrt","version":"Chaos Calmer","revision":"r47055","codename":"omnia","target":"mvebu/generic","description":"OpenWrt omnia 15.05"}})

```
config vpn-policy-routing 'config'
	option verbosity '2'
	option ipv6_enabled '0'
	option udp_proto_enabled '1'
	option strict_enforcement '1'
	list ignored_interface 'guest'
	list ignored_interface 'tun'
	option enabled '1'
	option dnsmasq_enabled '0'
	option ipset_enabled '1'
	option output_chain_enabled '1'
	option icmp_interface 'wg0'
```

`/etc/init.d/vpn-policy-routing reload`

> Creating table 'wan/84..x.x.x' [✓]
> Creating table 'wg0/192.168.112.12' [✓]
> Routing 's5' via wan [✓]
> Routing 's1' via wan [✓]
> Routing 'da' via wan [✓]
> Routing '1750e' via wan [✓]
> Routing 'dvb-c' via wan [✓]
> Routing 'stv9s' via wan [✓]
> Routing 'oc_vpscp' via wan [✓]
> Routing 'oc_vnc' via wan [✓]
> Routing 'oc_ssh' via wan [✓]
> Routing 'lan' via wan [✓]
> vpn-policy-routing 0.0.2-17 started on wan/84.x.x.x wg0/192.168.112.12 [✓]
> vpn-policy-routing 0.0.2-17 monitoring interfaces: wan wg0 [✓]

`/etc/init.d/vpn-policy-routing support`

> vpn-policy-routing 0.0.2-17 running on OpenWrt Chaos Calmer. WAN (IPv4): wan/dev/84.x.x.x.

> Dnsmasq version 2.78  Copyright (c) 2000-2017 Simon Kelley
> Compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify

> Routes/IP Rules
> default         ppp-gw-pop107.r 0.0.0.0         UG    0      0        0 pppoe-wan
> IPv4 Table 201: default via 84.x.x.x dev pppoe-wan
> IPv4 Table 201 Rules:
> 32560:  from all fwmark 0x10000 lookup 201
> IPv4 Table 202: default via 192.168.112.12 dev br-lan
> IPv4 Table 202 Rules:
> 32559:  from all fwmark 0x20000 lookup 202

> IP Tables PREROUTING
> -N VPR_PREROUTING
> -A VPR_PREROUTING -s 192.168.112.0/24 -m comment --comment lan -c 1625 127695 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -d 179.x.x.x/32 -p udp -m multiport --dports 56009 -m comment --comment oc_ssh -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -d 179.x.x.x/32 -p tcp -m multiport --dports 56009 -m comment --comment oc_ssh -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -d 179.x.x.x/32 -p udp -m multiport --dports 5904 -m comment --comment oc_vnc -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -d 179.x.x.x/32 -p tcp -m multiport --dports 5904 -m comment --comment oc_vnc -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -d 94.x.x.x/32 -p udp -m multiport --dports 4083 -m comment --comment oc_vpscp_vpscp_[obfuscated]_com -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -d 94.x.x.x/32 -p tcp -m multiport --dports 4083 -m comment --comment oc_vpscp_vpscp_[obfuscated]_com -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -s 192.168.112.122/32 -m comment --comment stv9s -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -s 192.168.112.191/32 -m comment --comment dvb-c -c 5 300 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -s 192.168.112.190/32 -m comment --comment 1750e -c 5 300 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -s 192.168.112.160/32 -m comment --comment da -c 2 837 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -s 192.168.112.121/32 -m comment --comment s1 -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -s 192.168.112.120/32 -m comment --comment s5 -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_PREROUTING -m set --match-set wg0 dst -c 0 0 -j MARK --set-xmark 0x20000/0xff0000
> -A VPR_PREROUTING -m set --match-set wan dst -c 0 0 -j MARK --set-xmark 0x10000/0xff0000

> IP Tables OUTPUT
> -N VPR_OUTPUT
> -A VPR_OUTPUT -d 179.x.x.x/32 -p udp -m multiport --dports 56009 -m comment --comment oc_ssh -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_OUTPUT -d 179.x.x.x/32 -p tcp -m multiport --dports 56009 -m comment --comment oc_ssh -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_OUTPUT -d 179.x.x.x/32 -p udp -m multiport --dports 5904 -m comment --comment oc_vnc -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_OUTPUT -d 179.x.x.x/32 -p tcp -m multiport --dports 5904 -m comment --comment oc_vnc -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_OUTPUT -d 94.x.x.x/32 -p udp -m multiport --dports 4083 -m comment --comment oc_vpscp_vpscp_[obfuscated]_com -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_OUTPUT -d 94.x.x.x/32 -p tcp -m multiport --dports 4083 -m comment --comment oc_vpscp_vpscp_[obfuscated]_com -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
> -A VPR_OUTPUT -p icmp -c 0 0 -j MARK --set-xmark 0x20000/0xff0000
> -A VPR_OUTPUT -m set --match-set wg0 dst -c 0 0 -j MARK --set-xmark 0x20000/0xff0000
> -A VPR_OUTPUT -m set --match-set wan dst -c 0 0 -j MARK --set-xmark 0x10000/0xff0000

> Current ipsets
> create wan hash:net family inet hashsize 1024 maxelem 65536 comment
> create wg0 hash:net family inet hashsize 1024 maxelem 65536 comment

> Your support details have been logged to '/var/vpn-policy-routing-support'. [✓]

**Comment by stangri** [comment]
Can you try the same with the OpenVPN tunnel?

**Comment by ghost** [comment]
I am afraid I do not have an ovpn server available/running at the moment...

**Comment by ghost** [comment]
With VPR _disabled_ and 

```
config wireguard_wg0
	list allowed_ips '0.0.0.0/0'
	option route_allowed_ips '1'
```
icmp traffic from the router and its clients are routed through the vpn with no issue (as expected).
