### ISSUE TITLE
enabling vpn-policy-routing blocks internal rdp

### ISSUE THREAD

**Issue by disclosurez** [stangri/openwrt_packages#82]
when I enable vpn-policy-routing, I can no longer RDP from another network segment

I need to be able to RDP from 192.168.0.0 to the 10.0.0.0 range, but when I enable this, RDP stops working, and the traffic is not allowed through.

any idea how to fix?

**Comment by stangri** [comment]
Please create a new issue using the [[vpn-policy-routing] Bug Report](https://github.com/stangri/openwrt_packages/issues/new?assignees=&labels=&template=-vpn-policy-routing--bug-report.md&title=%5Bvpn-policy-routing%5D+Issue%3A) and make sure to fully fill the template.
