### ISSUE TITLE
[vpn-policy-routing] Wish: route existing ipset

### ISSUE THREAD

**Issue by y-alexey** [stangri/openwrt_packages#91]
Please make it possible to directly point in the rules compliance with a particular ipset set. 
I have ready-made files for "ipset restore", parser and scripts for renew it.  These are many thousands of subnets and in this form it load much faster than one-by-one line.  If you app already have the opportunity to write a rules for matching a specific set, indicate how to do it.  I did not understand from the description.

**Comment by stangri** [comment]
> Please make it possible to directly point in the rules compliance with a particular ipset set.

There already is a documentation with two sample scripts for user-defined custom scripts. If your question is about something else, re-open (and you may want to comment in Russian, because I can't make sense of what you're asking in English).

**Comment by y-alexey** [comment]
Ок
Попробую подробно.

Как известно, существует проблема с блокировками ркн. Существует список имён и адресов. Имеется масса ресурсов, где это можно так или иначе получить. Результат обработки лежит у меня в репозитории в виде оптимальном для загрузки в ipset/dnsmasq бытового роутера.

Сейчас это работает либо с заворотом всего совпадающего в прозрачный прокси tor с помощью port forward правил fw3, либо с помощью прямого указания имени ipset в правилах mwan3 для VPN интерфейса.

Хотелось бы в идеале получить приоритетную маршрутизацию в VPN, а если он лежит, то в tor. Я не уверен, что ваше решение может с этим помочь, потому и спрашиваю.

В примерах у вас просто списки. И загружается всё в фиксированный сет. Загрузка списка подсетей и хостов в созданный вашим приложением сет может оказаться в разы дольше, чем выполнение команды ipset restore/swap. Вот в этом вопрос. Не указывать в правилах файл с хостами, а указывать имя сета с сотней тысяч позиций. Точнее, имена разных сетов или сета типа list, содержащего разные сеты (IP, net). Периодически обновляющегося внешним скриптом без перезагрузки конфигурации и изменения правил маршрутизации.

**Comment by stangri** [comment]
Так сделайте ipset rename/swap в user-скрипте. А в скрипте обновления -- обновляйте ipset созданный VPR если он есть и ваш собственный, если нет.

PS. Жду примера заворота трафика в Тор через VPR в соседнем issue.

**Comment by y-alexey** [comment]
Я там выше поправил. Одним сетом можно обойтись только если это будет list. Но если ваша программа создаёт, например, hash:ip, то свопнуть его с list:set не выйдет.

**Comment by stangri** [comment]
> Я там выше поправил. Одним сетом можно обойтись только если это будет list. Но если ваша программа создаёт, например, hash:ip, то свопнуть его с list:set не выйдет.

Ну поправьте/добавьте тогда iptables rules в user-script. Я не понимаю чего вы хотите от VPR.

**Comment by y-alexey** [comment]
Чего я хочу, я прямо сразу сказал - чтобы одним из возможных критериев в правилах было совпадение с сетом, указанным по имени. Это наглядно и интуитивно прозрачно, что и требуется от пользовательских интерфейсов, обычно.

Относительно остального я подумаю. Ночь уже тут.

**Comment by stangri** [comment]
Эта возможность есть и реализуется через user-script в котором через ipt/iptables вы добавляете правила нацеленные на ваш сет. Можете посмотреть что создает программа через команду support и добавить аналогичные (я бы рекомендовал через ipt).

**Comment by y-alexey** [comment]
Давайте терминологию как-то согласуем. Я считаю, что то, что реализовано через написание правил iptables руками, не реализовано с помощью fw3, vpr или mwan3. И наоборот, эти программы реализуют лишь те функции, для которых сами создают в результате команды iptables.

Я вот чего понять не могу. Как, где и в результате чего ваш пакет создаёт сет. (FW3, например, имеет для этого "config ipset") И по какому принципу его называет? Я не могу же указать в ваших правилах своё имя сета?

Допустим, у меня есть три сета, и мне нужно совпадения пихать в конкретный интерфейс. Насколько я понял, мне тут ваш пакет вообще не поможет. А поможет прямое написание правил iptables руками для каждого сета. Или, всё-таки, есть возможность как-то на сеты ссылаться? Или можно их собрать в мета сет и на него сослаться в правилах vpr?
Я вижу в примере имя сета, как бы, совпадает с именем целевого интерфейса. Это так работает?
