### ISSUE TITLE
[wireshark-helper] Wish: Chooser for Interface

### ISSUE THREAD

**Issue by ElreboCM** [stangri/openwrt_packages#94]
**Is your feature request related to a problem? Please describe.**
urrently the interface is hardcoded to "br-lan". I need to capture packets in a different VLAN than default LAN. 

**Describe the solution you'd like**
Can you include a configuration option and possible a chooser or textfield int he luck app for setting the interface?

**Comment by stangri** [comment]
Can you please attach your /etc/config/network file so I could test vlan support in Luci?

**Comment by ElreboCM** [comment]
Sure there you go

config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'xxxx:xxxx:xxxx::/48'

config interface 'wan'
	option ifname 'eth0'
	option proto 'static'
	option ipaddr 'XX.XX.XX.XX'
	option netmask '255.255.255.252'
	option gateway 'XX.XX.XX.XX'
	option dns '8.8.8.8 8.8.4.4'

config interface 'lan'
	option type 'bridge'
	option proto 'static'
	option netmask '255.255.255.0'
	option _turris_mode 'managed'
	option ip6assign '60'
	option bridge_empty '1'
	option ifname 'lan1 lan2 lan3'
	option ipaddr '192.168.1.1'

config interface 'wan6'
	option ifname '@wan'
	option proto 'dhcpv6'

config interface 'VLAN1'
	option proto 'static'
	option ifname 'lan4'
	option ipaddr '192.168.2.1'
	option netmask '255.255.255.0'

**Comment by stangri** [comment]
So for VLAN1, how would the proper iptables rule look?

Unless there's an interface for VLAN, I'm not sure if iptables would be enough per: https://serverfault.com/a/505441/295640

**Comment by ElreboCM** [comment]
In my case it is sufficient to use lan4 instead of br-lan in your Script as my Vlan is associated with that physical port.

**Comment by stangri** [comment]
Pease test luci-app-wireshark-helper (git-20.093.52499-3fd5c07-5) and  wireshark-helper (0.0.1-3) from my repo.

**Comment by ElreboCM** [comment]
I tried it unfortuneatly the chooser shows only one option (LAN).

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/4703830/78269103-69e51e00-7509-11ea-834d-08cd24f49fc4.png">

**Comment by ElreboCM** [comment]
I have not quite figured out how you fill the chooser with items. 
I guess it would be best to have br-lan as default (bridging the lan ethernet ports and wifi) and include as well all physical interfaces as in this chooser:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/4703830/78298190-c2301600-7531-11ea-8afa-76017bc6ba6a.png">


There must be a way to read in these interfaces. Though I don't know how.

**Comment by stangri** [comment]
> I tried it unfortuneatly the chooser shows only one option (LAN).
> 

Please remove current luci app, refresh opkg lists and install it again. I've updated the app while keeping the same version number.

**Comment by ElreboCM** [comment]
Works fine! Thank you!
