### ISSUE TITLE
[vpn-policy-routing] Issue: Gateway discovery delay

### ISSUE THREAD

**Issue by bunbury86** [stangri/openwrt_packages#97]
Hi,
when starting the service after a reboot or the connection, if the VPN is slow to connect the gateway detection ends with VPN gateway (openvpn) set to 0.0.0.0

After the reload of the configuration, everything is ok.

I already tried to increase the gateway discovery timeout to 90 secs without improvements (from the code seems to work only for WAN)

Regards, Donatello

**Comment by stangri** [comment]
Can't reproduce: after VPN tunnel is established, VPR is reloaded with the correct gateway for me.
