### ISSUE TITLE
[vpn-policy-routing] Issue: Installation Instructions Failing

### ISSUE THREAD

**Issue by cxtal** [stangri/openwrt_packages#99]
Hello! Attempting an install on a fresh machine after installing all the requirements fails under OpenWrt 18.06.0-rc1 with the error:

```
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-vpn-policy-routing:
 * 	luci-compat * 
```

The router is a GLinet device and the firmware is installed from the official GLiNet repositories that apparently have not yet been updated to include the "fake" `luci-compat` package.

Can a note please be added to the documentation saying that `--force-depends` may have to be used to bypass the issue [just as you mentioned on the forums](https://forum.openwrt.org/t/luci-compat-and-18-06/48369/14)? 

Many thanks.

**Comment by stangri** [comment]
Thank you, closed via https://github.com/stangri/openwrt_packages/commit/53c1731b610cb45e1a238c7f894efcab2958c5f2.
